# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui',
# licensing of 'design.ui' applies.
#
# Created: Fri Jan 25 21:00:43 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 781)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(10, 430, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab)
        self.label_30.setGeometry(QtCore.QRect(10, 50, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(10, 80, 621, 371))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setWordWrap(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(600, 630, 481, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab)
        self.label_26.setGeometry(QtCore.QRect(10, 460, 641, 191))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_26.setWordWrap(True)
        self.label_26.setObjectName("label_26")
        self.label_31 = QtWidgets.QLabel(self.tab)
        self.label_31.setGeometry(QtCore.QRect(680, 80, 321, 381))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_31.setWordWrap(True)
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.tab)
        self.label_33.setGeometry(QtCore.QRect(10, 10, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setUnderline(True)
        font.setBold(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab)
        self.label_34.setGeometry(QtCore.QRect(680, 50, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(680, 450, 101, 101))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab)
        self.label_37.setGeometry(QtCore.QRect(800, 450, 111, 101))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(930, 450, 111, 101))
        self.label_38.setObjectName("label_38")
        self.label_version = QtWidgets.QLabel(self.tab)
        self.label_version.setGeometry(QtCore.QRect(20, 630, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.label_version.setFont(font)
        self.label_version.setObjectName("label_version")
        self.tabWidget.addTab(self.tab, "")
        self.tab_geometry = QtWidgets.QWidget()
        self.tab_geometry.setObjectName("tab_geometry")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_geometry)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_geometry)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.coordinates_tableWidget = QtWidgets.QTableWidget(self.tab_geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coordinates_tableWidget.sizePolicy().hasHeightForWidth())
        self.coordinates_tableWidget.setSizePolicy(sizePolicy)
        self.coordinates_tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.coordinates_tableWidget.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.coordinates_tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.coordinates_tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.coordinates_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.coordinates_tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.coordinates_tableWidget.setDragEnabled(True)
        self.coordinates_tableWidget.setAlternatingRowColors(False)
        self.coordinates_tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.coordinates_tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.coordinates_tableWidget.setObjectName("coordinates_tableWidget")
        self.coordinates_tableWidget.setColumnCount(5)
        self.coordinates_tableWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coordinates_tableWidget.setItem(3, 4, item)
        self.coordinates_tableWidget.horizontalHeader().setVisible(False)
        self.coordinates_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.coordinates_tableWidget.horizontalHeader().setDefaultSectionSize(140)
        self.coordinates_tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.coordinates_tableWidget.horizontalHeader().setStretchLastSection(False)
        self.coordinates_tableWidget.verticalHeader().setVisible(False)
        self.coordinates_tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.coordinates_tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.coordinates_tableWidget.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_7.addWidget(self.coordinates_tableWidget)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.addRowButton = QtWidgets.QToolButton(self.tab_geometry)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addRowButton.setIcon(icon)
        self.addRowButton.setObjectName("addRowButton")
        self.verticalLayout_5.addWidget(self.addRowButton)
        self.removeRowButton = QtWidgets.QToolButton(self.tab_geometry)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeRowButton.setIcon(icon1)
        self.removeRowButton.setObjectName("removeRowButton")
        self.verticalLayout_5.addWidget(self.removeRowButton)
        self.moveUpRowButton = QtWidgets.QToolButton(self.tab_geometry)
        self.moveUpRowButton.setObjectName("moveUpRowButton")
        self.verticalLayout_5.addWidget(self.moveUpRowButton)
        self.moveDownRowButton = QtWidgets.QToolButton(self.tab_geometry)
        self.moveDownRowButton.setObjectName("moveDownRowButton")
        self.verticalLayout_5.addWidget(self.moveDownRowButton)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.line = QtWidgets.QFrame(self.tab_geometry)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.label_2 = QtWidgets.QLabel(self.tab_geometry)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.graphicsViewGeometry = MyGeometryView(self.tab_geometry)
        self.graphicsViewGeometry.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsViewGeometry.setLineWidth(1)
        self.graphicsViewGeometry.setObjectName("graphicsViewGeometry")
        self.horizontalLayout_9.addWidget(self.graphicsViewGeometry)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_geometry, "")
        self.tab_materials = QtWidgets.QWidget()
        self.tab_materials.setObjectName("tab_materials")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_materials)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.InputGrid = QtWidgets.QGridLayout()
        self.InputGrid.setObjectName("InputGrid")
        self.Material = QtWidgets.QHBoxLayout()
        self.Material.setObjectName("Material")
        self.Input_verticalLayout = QtWidgets.QVBoxLayout()
        self.Input_verticalLayout.setObjectName("Input_verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Input_verticalLayout.addWidget(self.label_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_f_yk = QtWidgets.QLineEdit(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_f_yk.setFont(font)
        self.lineEdit_f_yk.setObjectName("lineEdit_f_yk")
        self.gridLayout_3.addWidget(self.lineEdit_f_yk, 2, 2, 1, 1)
        self.lineEdit_f_ck = QtWidgets.QLineEdit(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_f_ck.setFont(font)
        self.lineEdit_f_ck.setObjectName("lineEdit_f_ck")
        self.gridLayout_3.addWidget(self.lineEdit_f_ck, 0, 2, 1, 1)
        self.lineEdit_E_cm = QtWidgets.QLineEdit(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_E_cm.setFont(font)
        self.lineEdit_E_cm.setObjectName("lineEdit_E_cm")
        self.gridLayout_3.addWidget(self.lineEdit_E_cm, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.lineEdit_E_s = QtWidgets.QLineEdit(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_E_s.setFont(font)
        self.lineEdit_E_s.setObjectName("lineEdit_E_s")
        self.gridLayout_3.addWidget(self.lineEdit_E_s, 3, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 2, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 2, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 4, 3, 1, 1)
        self.lineEdit_alpha_cc = QtWidgets.QLineEdit(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_alpha_cc.setFont(font)
        self.lineEdit_alpha_cc.setObjectName("lineEdit_alpha_cc")
        self.gridLayout_3.addWidget(self.lineEdit_alpha_cc, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 5, 0, 1, 1)
        self.comboBox_nu = QtWidgets.QComboBox(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_nu.setFont(font)
        self.comboBox_nu.setObjectName("comboBox_nu")
        self.comboBox_nu.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_nu, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 5, 3, 1, 1)
        self.Input_verticalLayout.addLayout(self.gridLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Input_verticalLayout.addItem(spacerItem2)
        self.Material.addLayout(self.Input_verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Material.addItem(spacerItem3)
        self.InputGrid.addLayout(self.Material, 0, 0, 1, 1)
        self.Analysis = QtWidgets.QHBoxLayout()
        self.Analysis.setObjectName("Analysis")
        self.Input_verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.Input_verticalLayout_2.setObjectName("Input_verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Input_verticalLayout_2.addWidget(self.label_4)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.comboBox_concrete = QtWidgets.QComboBox(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_concrete.setFont(font)
        self.comboBox_concrete.setObjectName("comboBox_concrete")
        self.comboBox_concrete.addItem("")
        self.comboBox_concrete.addItem("")
        self.comboBox_concrete.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_concrete)
        self.label_11 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.comboBox_reinf = QtWidgets.QComboBox(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_reinf.setFont(font)
        self.comboBox_reinf.setObjectName("comboBox_reinf")
        self.comboBox_reinf.addItem("")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_reinf)
        self.label_22 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.Input_verticalLayout_2.addLayout(self.formLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_gamma_c = QtWidgets.QLineEdit(self.tab_materials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_gamma_c.sizePolicy().hasHeightForWidth())
        self.lineEdit_gamma_c.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_gamma_c.setFont(font)
        self.lineEdit_gamma_c.setObjectName("lineEdit_gamma_c")
        self.gridLayout_4.addWidget(self.lineEdit_gamma_c, 1, 1, 1, 1)
        self.lineEdit_gamma_s = QtWidgets.QLineEdit(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_gamma_s.setFont(font)
        self.lineEdit_gamma_s.setObjectName("lineEdit_gamma_s")
        self.gridLayout_4.addWidget(self.lineEdit_gamma_s, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_materials)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_materials)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 1, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 3, 2, 1, 1)
        self.Input_verticalLayout_2.addLayout(self.gridLayout_4)
        self.checkBox_analSLS_1 = QtWidgets.QCheckBox(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_analSLS_1.setFont(font)
        self.checkBox_analSLS_1.setChecked(True)
        self.checkBox_analSLS_1.setObjectName("checkBox_analSLS_1")
        self.Input_verticalLayout_2.addWidget(self.checkBox_analSLS_1)
        self.checkBox_analULS_1 = QtWidgets.QCheckBox(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_analULS_1.setFont(font)
        self.checkBox_analULS_1.setChecked(False)
        self.checkBox_analULS_1.setObjectName("checkBox_analULS_1")
        self.Input_verticalLayout_2.addWidget(self.checkBox_analULS_1)
        self.checkBox_analULS_2 = QtWidgets.QCheckBox(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(True)
        self.checkBox_analULS_2.setFont(font)
        self.checkBox_analULS_2.setCheckable(False)
        self.checkBox_analULS_2.setObjectName("checkBox_analULS_2")
        self.Input_verticalLayout_2.addWidget(self.checkBox_analULS_2)
        self.checkBox_analSLS_2 = QtWidgets.QCheckBox(self.tab_materials)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setStrikeOut(True)
        self.checkBox_analSLS_2.setFont(font)
        self.checkBox_analSLS_2.setCheckable(False)
        self.checkBox_analSLS_2.setObjectName("checkBox_analSLS_2")
        self.Input_verticalLayout_2.addWidget(self.checkBox_analSLS_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Input_verticalLayout_2.addItem(spacerItem4)
        self.Analysis.addLayout(self.Input_verticalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Analysis.addItem(spacerItem5)
        self.InputGrid.addLayout(self.Analysis, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.InputGrid)
        self.PlotLayout = QtWidgets.QVBoxLayout()
        self.PlotLayout.setObjectName("PlotLayout")
        self.graphicsViewConcrete = QtWidgets.QGraphicsView(self.tab_materials)
        self.graphicsViewConcrete.setObjectName("graphicsViewConcrete")
        self.PlotLayout.addWidget(self.graphicsViewConcrete)
        self.graphicsViewReinforcement = QtWidgets.QGraphicsView(self.tab_materials)
        self.graphicsViewReinforcement.setObjectName("graphicsViewReinforcement")
        self.PlotLayout.addWidget(self.graphicsViewReinforcement)
        self.horizontalLayout.addLayout(self.PlotLayout)
        self.tabWidget.addTab(self.tab_materials, "")
        self.tab_loading = QtWidgets.QWidget()
        self.tab_loading.setObjectName("tab_loading")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_loading)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SectionForces_tableWidget = QtWidgets.QTableWidget(self.tab_loading)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SectionForces_tableWidget.sizePolicy().hasHeightForWidth())
        self.SectionForces_tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.SectionForces_tableWidget.setFont(font)
        self.SectionForces_tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.SectionForces_tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.SectionForces_tableWidget.setObjectName("SectionForces_tableWidget")
        self.SectionForces_tableWidget.setColumnCount(6)
        self.SectionForces_tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.SectionForces_tableWidget.setItem(0, 5, item)
        self.SectionForces_tableWidget.horizontalHeader().setVisible(False)
        self.SectionForces_tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.SectionForces_tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.SectionForces_tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.SectionForces_tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.SectionForces_tableWidget.horizontalHeader().setStretchLastSection(False)
        self.SectionForces_tableWidget.verticalHeader().setVisible(False)
        self.SectionForces_tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.SectionForces_tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.SectionForces_tableWidget.verticalHeader().setSortIndicatorShown(True)
        self.SectionForces_tableWidget.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.SectionForces_tableWidget)
        self.load_fac_label = QtWidgets.QLabel(self.tab_loading)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.load_fac_label.setFont(font)
        self.load_fac_label.setObjectName("load_fac_label")
        self.horizontalLayout_2.addWidget(self.load_fac_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.tab_loading)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.lineEdit_wallNodeN = QtWidgets.QLineEdit(self.tab_loading)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_wallNodeN.sizePolicy().hasHeightForWidth())
        self.lineEdit_wallNodeN.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_wallNodeN.setFont(font)
        self.lineEdit_wallNodeN.setObjectName("lineEdit_wallNodeN")
        self.verticalLayout_6.addWidget(self.lineEdit_wallNodeN)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem7)
        self.label_16 = QtWidgets.QLabel(self.tab_loading)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_6.addWidget(self.label_16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.graphicsViewResults = MyResultView(self.tab_loading)
        self.graphicsViewResults.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsViewResults.setObjectName("graphicsViewResults")
        self.horizontalLayout_4.addWidget(self.graphicsViewResults)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_analyse = QtWidgets.QPushButton(self.tab_loading)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_analyse.setFont(font)
        self.pushButton_analyse.setObjectName("pushButton_analyse")
        self.verticalLayout_3.addWidget(self.pushButton_analyse)
        self.checkBox_plot1 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot1.setChecked(False)
        self.checkBox_plot1.setObjectName("checkBox_plot1")
        self.verticalLayout_3.addWidget(self.checkBox_plot1)
        self.checkBox_plot2 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot2.setChecked(False)
        self.checkBox_plot2.setObjectName("checkBox_plot2")
        self.verticalLayout_3.addWidget(self.checkBox_plot2)
        self.checkBox_plot3 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot3.setChecked(False)
        self.checkBox_plot3.setObjectName("checkBox_plot3")
        self.verticalLayout_3.addWidget(self.checkBox_plot3)
        self.checkBox_plot4 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot4.setChecked(False)
        self.checkBox_plot4.setObjectName("checkBox_plot4")
        self.verticalLayout_3.addWidget(self.checkBox_plot4)
        self.checkBox_plot5 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot5.setChecked(False)
        self.checkBox_plot5.setObjectName("checkBox_plot5")
        self.verticalLayout_3.addWidget(self.checkBox_plot5)
        self.checkBox_plot6 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot6.setObjectName("checkBox_plot6")
        self.verticalLayout_3.addWidget(self.checkBox_plot6)
        self.checkBox_plot7 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot7.setObjectName("checkBox_plot7")
        self.verticalLayout_3.addWidget(self.checkBox_plot7)
        self.checkBox_plot8 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot8.setObjectName("checkBox_plot8")
        self.verticalLayout_3.addWidget(self.checkBox_plot8)
        self.checkBox_plot9 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot9.setObjectName("checkBox_plot9")
        self.verticalLayout_3.addWidget(self.checkBox_plot9)
        self.checkBox_plot10 = QtWidgets.QCheckBox(self.tab_loading)
        self.checkBox_plot10.setObjectName("checkBox_plot10")
        self.verticalLayout_3.addWidget(self.checkBox_plot10)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.tabWidget.addTab(self.tab_loading, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.openAct = QtWidgets.QAction(MainWindow)
        self.openAct.setObjectName("openAct")
        self.saveAct = QtWidgets.QAction(MainWindow)
        self.saveAct.setObjectName("saveAct")
        self.exitAct = QtWidgets.QAction(MainWindow)
        self.exitAct.setObjectName("exitAct")
        self.menuFile.addAction(self.openAct)
        self.menuFile.addAction(self.saveAct)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exitAct)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.openAct)
        self.toolBar.addAction(self.saveAct)
        self.toolBar.addAction(self.exitAct)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Hollow section analysis tool", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("MainWindow", "Assumptions and limitations:", None, -1))
        self.label_30.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.label_24.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>This is a design tool for analysis of hollow reinforced concrete sections under combined loading, fully embracing the interactions between bending and shear behaviour.</p><p>The complete interaction between bending and shear meant replacing the simple diagonal truss model with a more numerical extensive approach evolving a series of numerical optimization routines all based on achieving better fulfilment of equilibrium and for Service Limit State also elastic complementary energy for strain compatibility. The designer will therefore not need to deal with additional longitudinal reinforcement to cope with a separate shear demand.</p><p>The approach is similar to applying the Grashof\'s formula for thin-walled steel-sections for determining shear flow etc. however here without the basic assumption of linear elastic material behaviour unsuitable for reinforced concrete.</p><p>This method will provide designers with a superior insight into the actual stress state during Service Limit State including the transverse reinforcement in the circumferential direction and will avoid any superposition of lower bound methods and the corresponding strain compatibility violations typically applied with separate shear and bending analysis.</p><p>For Ultimate Limit State this tool will allow for an enhanced capacity of the cross-section as it determines an optimal shear flow distribution within the yield conditions of reinforced disks.</p></body></html>", None, -1))
        self.label_25.setText(QtWidgets.QApplication.translate("MainWindow", "Written by Kenneth C. Kleissl with funding from the COWI Foundation ", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>The implementation is based on the following assumptions:</p><p>- The span to depth ratio of the section is sufficient for beam theory to be applicable where plane section analysis approach is considered.</p><p>- The walls are sufficient thin, compared to the cross-section dimensions, for a thin-walled approach to be applicable.</p><p>- Normal stresses in the circumferential direction are neglected even though equilibrium in principle requires the presence of these. This is a common approach when analysing thin-walled sections.</p></body></html>", None, -1))
        self.label_31.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" text-decoration: underline;\">Axis</span><br/>Positive x towards right<br/>Positive y upward</p><p><span style=\" text-decoration: underline;\">Geometry</span><br/>The section must be defined in the clock-wise direction<br/>Angles are taken positive in the counter-clockwise direction starting from the x-axis</p><p><span style=\" text-decoration: underline;\">Section forces</span><br/>Positive Mx yields compression in the top<br/>Positive My yields compression on the left side<br/>Negative N yields compression<br/>Positive Vx yields shear in the x-direction (right)<br/>Positive Vy yields shear in the y-direction (upward)<br/>Positive T yields counter-clockwise shear flow<br/>Note that the above sign definitions follows a left hand system (LHS)</p></body></html>", None, -1))
        self.label_33.setText(QtWidgets.QApplication.translate("MainWindow", "General Design of Hollow RC Sections under Combined Actions", None, -1))
        self.label_34.setText(QtWidgets.QApplication.translate("MainWindow", "Sign convention", None, -1))
        self.label_36.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/Figures/coordinates.PNG\"/></p></body></html>", None, -1))
        self.label_37.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/Figures/force_sign_convention.PNG\"/></p></body></html>", None, -1))
        self.label_38.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><img src=\":/Figures/moment_sign_convention.PNG\"/></p></body></html>", None, -1))
        self.label_version.setText(QtWidgets.QApplication.translate("MainWindow", "v1.0", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Define starting coordinates and properties of each wall element here:", None, -1))
        self.coordinates_tableWidget.setSortingEnabled(False)
        self.coordinates_tableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Node no. 1", None, -1))
        self.coordinates_tableWidget.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Node no. 2", None, -1))
        self.coordinates_tableWidget.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Node no. 3", None, -1))
        self.coordinates_tableWidget.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Node no. 4", None, -1))
        self.coordinates_tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "X-coordinate", None, -1))
        self.coordinates_tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Y-coordinate", None, -1))
        self.coordinates_tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Wall thickness", None, -1))
        self.coordinates_tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Reinf. ratio long.", None, -1))
        self.coordinates_tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Reinf. ratio trans.", None, -1))
        __sortingEnabled = self.coordinates_tableWidget.isSortingEnabled()
        self.coordinates_tableWidget.setSortingEnabled(False)
        self.coordinates_tableWidget.item(0, 0).setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.coordinates_tableWidget.item(0, 1).setText(QtWidgets.QApplication.translate("MainWindow", "2000", None, -1))
        self.coordinates_tableWidget.item(0, 2).setText(QtWidgets.QApplication.translate("MainWindow", "300", None, -1))
        self.coordinates_tableWidget.item(0, 3).setText(QtWidgets.QApplication.translate("MainWindow", "0.01", None, -1))
        self.coordinates_tableWidget.item(0, 4).setText(QtWidgets.QApplication.translate("MainWindow", "0.01", None, -1))
        self.coordinates_tableWidget.item(1, 0).setText(QtWidgets.QApplication.translate("MainWindow", "1500", None, -1))
        self.coordinates_tableWidget.item(1, 1).setText(QtWidgets.QApplication.translate("MainWindow", "2000", None, -1))
        self.coordinates_tableWidget.item(1, 2).setText(QtWidgets.QApplication.translate("MainWindow", "200", None, -1))
        self.coordinates_tableWidget.item(1, 3).setText(QtWidgets.QApplication.translate("MainWindow", "0.01", None, -1))
        self.coordinates_tableWidget.item(1, 4).setText(QtWidgets.QApplication.translate("MainWindow", "0.01", None, -1))
        self.coordinates_tableWidget.item(2, 0).setText(QtWidgets.QApplication.translate("MainWindow", "1500", None, -1))
        self.coordinates_tableWidget.item(2, 1).setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.coordinates_tableWidget.item(2, 2).setText(QtWidgets.QApplication.translate("MainWindow", "300", None, -1))
        self.coordinates_tableWidget.item(2, 3).setText(QtWidgets.QApplication.translate("MainWindow", "0.01", None, -1))
        self.coordinates_tableWidget.item(2, 4).setText(QtWidgets.QApplication.translate("MainWindow", "0.01", None, -1))
        self.coordinates_tableWidget.item(3, 0).setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.coordinates_tableWidget.item(3, 1).setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.coordinates_tableWidget.item(3, 2).setText(QtWidgets.QApplication.translate("MainWindow", "200", None, -1))
        self.coordinates_tableWidget.item(3, 3).setText(QtWidgets.QApplication.translate("MainWindow", "0.01", None, -1))
        self.coordinates_tableWidget.item(3, 4).setText(QtWidgets.QApplication.translate("MainWindow", "0.01", None, -1))
        self.coordinates_tableWidget.setSortingEnabled(__sortingEnabled)
        self.addRowButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Insert new row at the bottom", None, -1))
        self.addRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "add", None, -1))
        self.removeRowButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Remove selected row", None, -1))
        self.removeRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "remove", None, -1))
        self.moveUpRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "move up", None, -1))
        self.moveDownRowButton.setText(QtWidgets.QApplication.translate("MainWindow", "move down", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Cross-section geometry:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_geometry), QtWidgets.QApplication.translate("MainWindow", "Geometry", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Material properties:", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "MPa", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>E<span style=\" vertical-align:sub;\">cm</span> = </p></body></html>", None, -1))
        self.lineEdit_f_yk.setText(QtWidgets.QApplication.translate("MainWindow", "500", None, -1))
        self.lineEdit_f_ck.setText(QtWidgets.QApplication.translate("MainWindow", "45", None, -1))
        self.lineEdit_E_cm.setText(QtWidgets.QApplication.translate("MainWindow", "35", None, -1))
        self.label_12.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>f<span style=\" vertical-align:sub;\">ck</span> = </p></body></html>", None, -1))
        self.lineEdit_E_s.setText(QtWidgets.QApplication.translate("MainWindow", "210", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>f<span style=\" vertical-align:sub;\">yk</span> = </p></body></html>", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p>E<span style=\" vertical-align:sub;\">s</span> = </p></body></html>", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("MainWindow", "GPa", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("MainWindow", "MPa", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("MainWindow", "GPa", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "-", None, -1))
        self.lineEdit_alpha_cc.setText(QtWidgets.QApplication.translate("MainWindow", "0.85", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Symbol\'; font-size:large;\">a</span><span style=\" vertical-align:sub;\">c</span> = </p></body></html>", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Symbol\'; font-size:large;\">n</span><span style=\" vertical-align:sub;\"></span> = </p></body></html>", None, -1))
        self.comboBox_nu.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "0.6 ( 1 - f_ck / 250 )", None, -1))
        self.label_10.setText(QtWidgets.QApplication.translate("MainWindow", "comp. strength eff. factor", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Analysis:", None, -1))
        self.comboBox_concrete.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "EN Parabolic-rectangular", None, -1))
        self.comboBox_concrete.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "EN Bi-linear", None, -1))
        self.comboBox_concrete.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "EN Nonlinear", None, -1))
        self.label_11.setText(QtWidgets.QApplication.translate("MainWindow", "Reinforcement", None, -1))
        self.comboBox_reinf.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Elastic-plastic", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("MainWindow", "Concrete", None, -1))
        self.lineEdit_gamma_c.setText(QtWidgets.QApplication.translate("MainWindow", "1.5", None, -1))
        self.lineEdit_gamma_s.setText(QtWidgets.QApplication.translate("MainWindow", "1.15", None, -1))
        self.label_9.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Symbol\'; font-size:large;\">g</span><span style=\" vertical-align:sub;\">s</span> = </p></body></html>", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'Symbol\'; font-size:large;\">g</span><span style=\" vertical-align:sub;\">c</span> = </p></body></html>", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("MainWindow", "-       ", None, -1))
        self.label_35.setText(QtWidgets.QApplication.translate("MainWindow", "-       ", None, -1))
        self.checkBox_analSLS_1.setText(QtWidgets.QApplication.translate("MainWindow", "Plane dual-section && sigma-tau equilibrium (SLS). Note: use linear elastic stress-strain for consistency with disk stresses", None, -1))
        self.checkBox_analULS_1.setText(QtWidgets.QApplication.translate("MainWindow", "Plane section && optimizing tau (ULS)", None, -1))
        self.checkBox_analULS_2.setText(QtWidgets.QApplication.translate("MainWindow", "Optimizing sigma && tau (extreme ULS)", None, -1))
        self.checkBox_analSLS_2.setText(QtWidgets.QApplication.translate("MainWindow", "Minimizing comp. elastic energy for sigma && tau (extreme SLS)", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_materials), QtWidgets.QApplication.translate("MainWindow", "Materials && Analysis", None, -1))
        self.SectionForces_tableWidget.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "LC", None, -1))
        self.SectionForces_tableWidget.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "N [kN]", None, -1))
        self.SectionForces_tableWidget.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Mx [kNm]", None, -1))
        self.SectionForces_tableWidget.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "My [kNm]", None, -1))
        self.SectionForces_tableWidget.horizontalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Vx [kN]", None, -1))
        self.SectionForces_tableWidget.horizontalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Vy [kN]", None, -1))
        self.SectionForces_tableWidget.horizontalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "T [kNm]", None, -1))
        __sortingEnabled = self.SectionForces_tableWidget.isSortingEnabled()
        self.SectionForces_tableWidget.setSortingEnabled(False)
        self.SectionForces_tableWidget.item(0, 0).setText(QtWidgets.QApplication.translate("MainWindow", "-15000", None, -1))
        self.SectionForces_tableWidget.item(0, 1).setText(QtWidgets.QApplication.translate("MainWindow", "20000", None, -1))
        self.SectionForces_tableWidget.item(0, 2).setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.SectionForces_tableWidget.item(0, 3).setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.SectionForces_tableWidget.item(0, 4).setText(QtWidgets.QApplication.translate("MainWindow", "5000", None, -1))
        self.SectionForces_tableWidget.item(0, 5).setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.SectionForces_tableWidget.setSortingEnabled(__sortingEnabled)
        self.load_fac_label.setText(QtWidgets.QApplication.translate("MainWindow", "No load-factor currently applied", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "No. of data points pr. wall element:", None, -1))
        self.lineEdit_wallNodeN.setText(QtWidgets.QApplication.translate("MainWindow", "25", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Plot results (positive value drawn on the outside of the section). Click to read values in statusbar.", None, -1))
        self.pushButton_analyse.setText(QtWidgets.QApplication.translate("MainWindow", "Analyse", None, -1))
        self.checkBox_plot1.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.checkBox_plot2.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.checkBox_plot3.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.checkBox_plot4.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.checkBox_plot5.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.checkBox_plot6.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.checkBox_plot7.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.checkBox_plot8.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.checkBox_plot9.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.checkBox_plot10.setText(QtWidgets.QApplication.translate("MainWindow", "no plot data available", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_loading), QtWidgets.QApplication.translate("MainWindow", "Loading && Results", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.toolBar.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "toolBar", None, -1))
        self.openAct.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.saveAct.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.saveAct.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+S", None, -1))
        self.exitAct.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.exitAct.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Exit application", None, -1))
        self.exitAct.setShortcut(QtWidgets.QApplication.translate("MainWindow", "Ctrl+Q", None, -1))

from Plots import MyGeometryView, MyResultView
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

